[global]
script_root = ""
script_root_env_var_name = ""

[alias.default.mapping]
alias-1 = { cmd = "ls -l" }
alias-2 = { cmd = "cd ~" }

[alias.alias-group-1.mapping]
alias-1-1 = { cmd = "ls -l" }
alias-1-2 = { cmd = "cd ~" }
